### ISSUE TITLE
RuntimeException in common.util.CryptoUtil.hmac() should include its cause

### ISSUE THREAD

**Issue by franferrax** [ongres/scram#18]
Hi, this is Francisco from the _OpenJDK_ team at _Red Hat_.

While working in [Red Hat Customer Portal: postgresql jdbc driver not able to connect in FIPS mode](https://access.redhat.com/solutions/6957637) (also reported in [StackOverflow: How to configure openjdk for FIPS and simple postgres connection example](https://stackoverflow.com/questions/71740204)), I've spotted the following minor issue:
https://github.com/ongres/scram/blob/779351d5a5d74a8f886da42190b4948c80735cbe/common/src/main/java/com/ongres/scram/common/util/CryptoUtil.java#L143-L151

The exception thrown at line 147 should include `e` as its cause, this way, the stack trace would include subsequent `Caused by:` parts with useful debug information:
```java
            throw new RuntimeException("Platform error: unsupported key for HMAC algorithm", e);
```

#### Current stack trace:
```
org.postgresql.util.PSQLException: Something unusual has occurred to cause the driver to fail. Please report this exception.
               at org.postgresql.Driver.connect(Driver.java:280)
               at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
               at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
               at gms.pgtest.PostgreSQLJDBC.connect(PostgreSQLJDBC.java:24)
               at gms.pgtest.PostgreSQLJDBC.main(PostgreSQLJDBC.java:41)
Caused by: java.lang.RuntimeException: Platform error: unsupported key for HMAC algorithm
               at org.postgresql.shaded.com.ongres.scram.common.util.CryptoUtil.hmac(CryptoUtil.java:147)
               at org.postgresql.shaded.com.ongres.scram.common.ScramMechanisms.hmac(ScramMechanisms.java:143)
               at org.postgresql.shaded.com.ongres.scram.common.ScramFunctions.hmac(ScramFunctions.java:70)
               at org.postgresql.shaded.com.ongres.scram.common.ScramFunctions.clientKey(ScramFunctions.java:85)
               at org.postgresql.shaded.com.ongres.scram.client.ScramSession$ClientFinalProcessor.<init>(ScramSession.java:188)
               at org.postgresql.shaded.com.ongres.scram.client.ScramSession$ClientFinalProcessor.<init>(ScramSession.java:194)
               at org.postgresql.shaded.com.ongres.scram.client.ScramSession$ClientFinalProcessor.<init>(ScramSession.java:163)
               at org.postgresql.shaded.com.ongres.scram.client.ScramSession$ServerFirstProcessor.clientFinalProcessor(ScramSession.java:130)
               at org.postgresql.jre7.sasl.ScramAuthenticator.processServerFirstMessage(ScramAuthenticator.java:147)
               at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:816)
               at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:180)
               at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:235)
               at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
               at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:223)
               at org.postgresql.Driver.makeConnection(Driver.java:400)
               at org.postgresql.Driver.connect(Driver.java:259)
               ... 4 more
```

**Comment by jorsol** [comment]
Hi Red Hat Team, it would be nice to have FIPS support, is there an easy way to test a FIPS-enabled container image like `ubi9/openjdk-21`?

**Comment by franferrax** [comment]
Hi @jorsol, as far as I know if you run a UBI image with `podman` in a FIPS-enabled host (e.g. Fedora or RHEL), FIPS-mode is [honored inside the container](https://github.com/containers/common/blob/v0.58.1/pkg/subscriptions/subscriptions.go#L307-L395). The main difficulty you will find is that the container's host must be in FIPS mode, as the Linux Kernel is shared between the host and the container, and the FIPS support has a Kernel component.

The following `podman` command can be used to check whether the container properly detected FIPS-mode from the host:

```bash
podman run -e CODE='
import java.security.Security;
boolean fipsCryptoPolicy = Security.getProperty("jdk.tls.disabledAlgorithms").contains("AES_256_CBC");
boolean fipsProvider = Security.getProvider("SunPKCS11-NSS-FIPS") != null;
String msg = fipsCryptoPolicy ? ( fipsProvider ?
        "OpenJDK is in FIPS-mode" : "Inconsistent state: only the FIPS crypto-policy is applied"
    ) : ( fipsProvider ?
        "Inconsistent state: only the FIPS provider is installed" : "OpenJDK is NOT in FIPS-mode"
    );
System.out.println(System.lineSeparator() + "**** " + msg);
' --rmi --rm registry.access.redhat.com/ubi8/openjdk-21:latest bash -c 'jshell --no-startup - <<<"$CODE"'
```

Output from a FIPS-enabled host:
```
Trying to pull registry.access.redhat.com/ubi8/openjdk-21:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob c3ab09ceaf64 done  
Copying blob 74e0c06e5eac done  
Copying config 03b78e2d0d done  
Writing manifest to image destination
Storing signatures
Apr 02, 2024 3:51:12 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.

**** OpenJDK is in FIPS-mode
```

Output from a FIPS-disabled host:
```
Trying to pull registry.access.redhat.com/ubi8/openjdk-21:latest...
Getting image source signatures
Checking if image destination supports signatures
Copying blob c3ab09ceaf64 done   | 
Copying blob 74e0c06e5eac done   | 
Copying config 03b78e2d0d done   | 
Writing manifest to image destination
Storing signatures
Apr 02, 2024 3:51:15 PM java.util.prefs.FileSystemPreferences$1 run
INFO: Created user preferences directory.

**** OpenJDK is NOT in FIPS-mode
```

Regards,\
Francisco

**Comment by jorsol** [comment]
> Hi @jorsol, as far as I know if you run a UBI image with `podman` in a FIPS-enabled host (e.g. Fedora or RHEL), FIPS-mode is [honored inside the container](https://github.com/containers/common/blob/v0.58.1/pkg/subscriptions/subscriptions.go#L307-L395). The main difficulty you will find is that the container's host must be in FIPS mode, as the Linux Kernel is shared between the host and the container, and the FIPS support has a Kernel component.
> 

I see, well luckily I use Fedora so I could test that.
