### ISSUE TITLE
Removing iterations >= 4096 check in ServerFirstMessage

### ISSUE THREAD

**Issue by sehrope** [ongres/scram#20]
While testing out some non-standard parameters for the pgjdbc driver, ran into this exception while using exactly one (1) iteration for SCRAM credentials:

```
FAILURE   0.1sec, org.postgresql.test.util.PasswordUtilTest > testCustomScramParams
    java.lang.RuntimeException: Failed to authenticate using supplied user and password
        at org.postgresql.test.util.PasswordUtilTest.assertValidUsernamePassword(PasswordUtilTest.java:41)
        at org.postgresql.test.util.PasswordUtilTest.testUserPassword(PasswordUtilTest.java:70)
        at org.postgresql.test.util.PasswordUtilTest.testCustomScramParams(PasswordUtilTest.java:146)
        Caused by: org.postgresql.util.PSQLException: Something unusual has occurred to cause the driver to fail. Please report this exception.
            at app//org.postgresql.Driver.connect(Driver.java:320)
            at platform/java.sql@17.0.9/java.sql.DriverManager.getConnection(DriverManager.java:681)
            at platform/java.sql@17.0.9/java.sql.DriverManager.getConnection(DriverManager.java:190)
            at app//org.postgresql.test.TestUtil.openDB(TestUtil.java:401)
            at app//org.postgresql.test.util.PasswordUtilTest.assertValidUsernamePassword(PasswordUtilTest.java:39)
            ... 2 more
            Caused by: java.lang.IllegalArgumentException: Argument 'iteration must be >= 4096' is not valid
                at com.ongres.scram.common.util.Preconditions.checkArgument(Preconditions.java:70)
                at com.ongres.scram.common.message.ServerFirstMessage.<init>(ServerFirstMessage.java:75)
                at com.ongres.scram.common.message.ServerFirstMessage.parseFrom(ServerFirstMessage.java:153)
                at com.ongres.scram.client.ScramSession$ServerFirstProcessor.<init>(ScramSession.java:107)
                at com.ongres.scram.client.ScramSession$ServerFirstProcessor.<init>(ScramSession.java:102)
                at com.ongres.scram.client.ScramSession.receiveServerFirstMessage(ScramSession.java:281)
                at org.postgresql.jre7.sasl.ScramAuthenticator.processServerFirstMessage(ScramAuthenticator.java:132)
                at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:863)
                at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:203)
                at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:258)
                at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:54)
                at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:263)
                at org.postgresql.Driver.makeConnection(Driver.java:444)
                at org.postgresql.Driver.connect(Driver.java:297)
                ... 6 more
```

The library is hard coded to to a minimum of 4096. I'd like to use a single iteration as the password itself is already long and cryptographically random (64 random bytes from /dev/urandom). The extra iterations are not needed to stretch the password and a single iteration would lend itself to faster connection startups.

Interestingly generating the credentials is fine and I'm pretty sure the server doesn't care about the iteration count. It's the Java client that is complaining that it does not want to try continuing with the SCRAM handshake because it thinks the server's suggested iteration count is too low.

Can the check be removed or disabled without compiling a custom version of the library?

Here's some precedent from the PG hackers list of people discussing the same idea: https://www.postgresql.org/message-id/1d669d97-86b3-a5dc-9f02-c368bca911f6%40iki.fi

**Comment by ahachete** [comment]
Hi, thanks for the suggestion @sehrope!

On one hand:
* The RFC is quite clear that "_For the SCRAM-SHA-1/SCRAM-SHA-1-PLUS SASL mechanism, servers SHOULD announce a hash iteration-count of at least 4096_" and in general I believe it's good to follow the RFC as much as possible and try to enforce or suggest best practices.
* This SCRAM library was written *for* the pgjdbc driver, but *not exclusively* for it, and should remain generic and design decisions should be independent of what Postgres does or doesn't.
* Despite what I just said, and for completeness: I don't like the Postgres connection latency in general, and it is high. But I also think that trying to reduce it be reducing the number of iterations is a questionable decision and IMO not the place to look into reducing such latency. (But this is off-topic in general).

On the other hand:
* Certainly the RFC still allows for different iterations, and in particular also mentions that the client has to use the iteration count used by the server (and that one could be lower than 4096). While this library is, again, not only for clients (could also be used for implementing servers), and enforcing at least 4096 may be a good practice, still I agree we should not force this minimum iteration count.

Would you be interested in providing a simple patch? Should remove this check and the associated Javadoc; but IMO to try to recommend best practices, should add an overloaded constructor without the `iteration` argument that sets it at 4096 (when not provided).

**Comment by sehrope** [comment]
Yes I can create a patch. It'd be in the source repo on GitLab right? (https://gitlab.com/ongresinc/scram)

Haven't checked out the code in detail, but I'm sure there's a way to retain the current minimum default value. It'd be an explicit opt-in to override it and use something smaller.

**Comment by jorsol** [comment]
This check will be reduced to 1 in the next release of SCRAM.
